nameOverride: backend
fullnameOverride: scoutli-backend

replicaCount: 1

image:
  repository: 147795259387.dkr.ecr.ap-southeast-1.amazonaws.com/scoutli-backend
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false # Backend tạm thời chưa cần Ingress, Frontend sẽ gọi qua Service nội bộ
