nameOverride: frontend
fullnameOverride: scoutli-frontend

replicaCount: 1

image:
  repository: 147795259387.dkr.ecr.ap-southeast-1.amazonaws.com/scoutli-frontend
  tag: "ca25c46e88aa53822fe53b685150245ea6df6a99" # CI sẽ update cái này
  pullPolicy: Always

service:
  type: ClusterIP # Với Ingress, Service chỉ cần là ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]' # Mặc định là 80
  hosts:
    - host: "" # Để trống để nhận mọi host, hoặc điền DNS nếu có
      paths:
        - path: /
          pathType: Prefix