apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scoutli-frontend-ingress
  namespace: scoutli-app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - www.journeywriter.space
      secretName: frontend-tls-secret
  rules:
    - host: www.journeywriter.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scoutli-frontend-scoutli-microservice
                port:
                  number: 80
