apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scoutli-frontend-ingress
  namespace: scoutli-app
  annotations:
    # Giữ lại annotation cũ cho tương thích ngược
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx # Thêm dòng này
  rules:
    - host: www.journeywriter.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scoutli-frontend-scoutli-microservice
                port:
                  number: 80